import type { Program } from "./types";

// 5-day rolling Upper/Lower pattern, built for the 12-week wedding block:
// Upper A → Lower A → Upper B → Lower B → Upper C → repeat. Cycle through in
// order regardless of calendar week. Priorities: waist (diet), glutes/hams,
// side delts, chest, arms at moderate volume, upper back for posture.
//
// Supersets are flagged in the coaching notes. Rest 30-45s between the pair,
// 60-90s after the pair. Heavy compounds stay as straight sets.
//
// Bump PROGRAM_VERSION whenever the template changes so saved state picks up
// the new program (sessions are kept, only the template is replaced).

export const PROGRAM_VERSION = 2;

let _id = 0;
const id = (p: string) => `${p}-${_id++}`;

const SS = (partner: string) =>
  `SUPERSET with ${partner}. 30-45s between, 60-90s after the pair.`;

export const SEED_PROGRAM: Program = {
  version: PROGRAM_VERSION,
  title: "5-Day Upper/Lower",
  days: [
    {
      id: "day-upper-a",
      name: "Upper A",
      subtitle: "heavy push + pull · preacher · lateral/triceps superset",
      exercises: [
        {
          id: id("ex"),
          name: "Bench press",
          targetSets: 4,
          targetReps: "6",
          restSeconds: 120,
          notes: "Heavy — RAMP FIRST: bar → 40 → 60 → 75 → working. Rest to 2 min as load climbs.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Lat pulldown",
          targetSets: 4,
          targetReps: "8",
          restSeconds: 60,
          notes: "Main vertical pull. Drive elbows down, full stretch at top.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Incline Smith (individual handle)",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 60,
          notes: "",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Seated row",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 60,
          notes: "",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Preacher curl",
          targetSets: 3,
          targetReps: "8",
          restSeconds: 60,
          notes: "Bottom position is the elbow's danger zone — drop load here FIRST if the elbow flares.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Cable lateral raise",
          targetSets: 3,
          targetReps: "15",
          restSeconds: 40,
          notes: `${SS("triceps pushdown")} In-and-out side to side.`,
          category: "push",
        },
        {
          id: id("ex"),
          name: "Triceps pushdown",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 40,
          notes: SS("cable lateral raise"),
          category: "push",
        },
      ],
    },
    {
      id: "day-lower-a",
      name: "Lower A",
      subtitle: "hinge + glute · hip thrust, RDL, sumo",
      exercises: [
        {
          id: id("ex"),
          name: "Hip thrust",
          targetSets: 4,
          targetReps: "8",
          restSeconds: 90,
          notes: "Main glute lift. RAMP FIRST: bar → ~60% → ~80% before working sets. Chin tucked, ribs down, squeeze hard at the top.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Romanian deadlift",
          targetSets: 3,
          targetReps: "8",
          restSeconds: 90,
          notes: "Hamstring sweep. Soft knees, push hips back, bar close to the legs. Stop where the hamstrings stop, not the lower back.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Smith sumo squat",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 60,
          notes: "Covers the squat pattern. Ramp the first set.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Seated glute abductor (spreaders)",
          targetSets: 3,
          targetReps: "20",
          restSeconds: 40,
          notes: SS("glute/ham hyperextension"),
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Glute/ham hyperextension",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 40,
          notes: `${SS("abductor")} STOP at a straight body — don't arch past neutral. Finish with a glute squeeze, not the lower back.`,
          category: "legs",
        },
      ],
    },
    {
      id: "day-upper-b",
      name: "Upper B",
      subtitle: "shoulders + arms · military press, DB laterals",
      exercises: [
        {
          id: id("ex"),
          name: "Military press",
          targetSets: 4,
          targetReps: "8",
          restSeconds: 90,
          notes: "Heavy — RAMP FIRST: bar → ~60% → ~80% before working sets.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "DB lateral raise",
          targetSets: 4,
          targetReps: "12",
          restSeconds: 40,
          notes: `${SS("face pull")} Heaviest lateral day — strict, lead with the elbows, no swing.`,
          category: "push",
        },
        {
          id: id("ex"),
          name: "Face pull",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 40,
          notes: `${SS("DB lateral raise")} Rear delts + upper back, posture work. Swap for DB shrugs if the cable is busy.`,
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Seated fly machine",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 60,
          notes: "Stretch position, controlled.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Incline DB curl",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 40,
          notes: `${SS("French press")} Long stretch at the bottom — if the elbow talks, shorten the range before dropping the set.`,
          category: "pull",
        },
        {
          id: id("ex"),
          name: "French press",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 40,
          notes: `${SS("incline DB curl")} 30kg was too heavy — ~20-22.5kg, slow & controlled. Hard on elbows; first thing to cut if they flare.`,
          category: "push",
        },
        {
          id: id("ex"),
          name: "Hammer curl",
          targetSets: 2,
          targetReps: "12",
          restSeconds: 40,
          notes: `${SS("overhead cable extension")} Forearms for rolled sleeves.`,
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Overhead cable extension",
          targetSets: 2,
          targetReps: "12",
          restSeconds: 40,
          notes: SS("hammer curl"),
          category: "push",
        },
      ],
    },
    {
      id: "day-lower-b",
      name: "Lower B",
      subtitle: "glute + quad · lunges, paused hip thrust",
      exercises: [
        {
          id: id("ex"),
          name: "Walking lunges (DB/KB)",
          targetSets: 3,
          targetReps: "10/leg",
          restSeconds: 60,
          notes: "First set bodyweight as a warmup, then loaded. Long stride, drive through the front heel for glutes.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Hip thrust",
          targetSets: 4,
          targetReps: "12",
          restSeconds: 60,
          notes: "Lighter than Lower A. 2-second pause and squeeze at the top of every rep.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Leg extension",
          targetSets: 3,
          targetReps: "15",
          restSeconds: 40,
          notes: `${SS("reverse hyper")} Maintenance pace.`,
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Reverse hyper",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 40,
          notes: `${SS("leg extension")} Controlled.`,
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Seated glute abductor (spreaders)",
          targetSets: 3,
          targetReps: "20",
          restSeconds: 45,
          notes: "Lean forward slightly for upper glute.",
          category: "legs",
        },
      ],
    },
    {
      id: "day-upper-c",
      name: "Upper C",
      subtitle: "hypertrophy push + pull · fly/rear delt, lateral/arm supersets",
      exercises: [
        {
          id: id("ex"),
          name: "Incline DB press",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 60,
          notes: "",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Lat pulldown (narrow)",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 60,
          notes: "",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Lying row (10° incline)",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 60,
          notes: "40kg felt heavy for 4x10 — hold and let reps come, or drop to 35kg.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Cable chest fly",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 40,
          notes: SS("cable rear delt fly"),
          category: "push",
        },
        {
          id: id("ex"),
          name: "Cable rear delt fly (individual)",
          targetSets: 3,
          targetReps: "15",
          restSeconds: 40,
          notes: `${SS("cable chest fly")} Supinated. Brisk.`,
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Cable lateral raise",
          targetSets: 3,
          targetReps: "15",
          restSeconds: 30,
          notes: "TRI-SET with cable curl + pushdown. 30s between, 60-90s after the three. In-and-out side to side.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Standing cable curl",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 30,
          notes: "TRI-SET with lateral raise + pushdown. 30s between, 60-90s after the three.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Triceps pushdown",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 30,
          notes: "TRI-SET with lateral raise + cable curl. 30s between, 60-90s after the three.",
          category: "push",
        },
      ],
    },
  ],
};
