import type { Program } from "./types";

// The 4-day template, ordered Pull / Push / Pull / Push to match how the
// program is actually being run. Coaching notes carry the adjustments we
// agreed: ramp sets on heavy compounds, hyper cue, load tweaks.

let _id = 0;
const id = (p: string) => `${p}-${_id++}`;

export const SEED_PROGRAM: Program = {
  title: "4-Day Upper Focus",
  days: [
    {
      id: "day-pull-a",
      name: "Pull A",
      subtitle: "back + biceps · posterior legs",
      exercises: [
        {
          id: id("ex"),
          name: "Lat pulldown",
          targetSets: 4,
          targetReps: "8",
          restSeconds: 60,
          notes: "Main vertical pull. Drive elbows down, full stretch at top.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Seated row",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 45,
          notes: "",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Lying row (10° incline)",
          targetSets: 4,
          targetReps: "10",
          restSeconds: 60,
          notes: "40kg felt heavy for 4x10 — hold and let reps come, or drop to 35kg.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Rear delt machine",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 45,
          notes: "",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Seated DB curl (upright)",
          targetSets: 4,
          targetReps: "8",
          restSeconds: 60,
          notes: "10kg dialed in. Watch the elbow — back off load before form.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Glute/ham hyperextension",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 60,
          notes: "STOP at a straight body — don't arch past neutral. Finish with a glute squeeze, not the lower back. If it still cramps, drop it and let reverse hypers carry the load.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Reverse hyper",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 60,
          notes: "Controlled, maintenance pace.",
          category: "legs",
        },
      ],
    },
    {
      id: "day-push-a",
      name: "Push A",
      subtitle: "shoulders/chest · quad + abductor legs",
      exercises: [
        {
          id: id("ex"),
          name: "Military press",
          targetSets: 3,
          targetReps: "6",
          restSeconds: 90,
          notes: "Heavy — RAMP FIRST: bar → ~60% → ~80% before working sets.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Flat DB press",
          targetSets: 4,
          targetReps: "8",
          restSeconds: 90,
          notes: "",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Incline Smith (individual handle)",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 60,
          notes: "",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Seated fly machine",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 45,
          notes: "Stretch position, controlled.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Cable lateral raise",
          targetSets: 3,
          targetReps: "15",
          restSeconds: 45,
          notes: "In-and-out side to side.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "French press",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 60,
          notes: "30kg was too heavy — drop to ~20-22.5kg, slow & controlled. Hard on elbows; back off if it talks.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Leg extension",
          targetSets: 3,
          targetReps: "15",
          restSeconds: 45,
          notes: "Maintenance pace.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Seated glute abductor (spreaders)",
          targetSets: 3,
          targetReps: "20",
          restSeconds: 45,
          notes: "",
          category: "legs",
        },
      ],
    },
    {
      id: "day-pull-b",
      name: "Pull B",
      subtitle: "back + biceps · posterior + squat legs",
      exercises: [
        {
          id: id("ex"),
          name: "Lat pulldown (narrow)",
          targetSets: 4,
          targetReps: "8",
          restSeconds: 60,
          notes: "",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Seated row (wide)",
          targetSets: 4,
          targetReps: "12",
          restSeconds: 45,
          notes: "",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Cable back pulldown",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 45,
          notes: "Straight-arm / lat-focused.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Preacher curl",
          targetSets: 4,
          targetReps: "6",
          restSeconds: 60,
          notes: "Bottom position is the elbow's danger zone — drop load here FIRST if the elbow flares.",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Standing cable curl",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 60,
          notes: "",
          category: "pull",
        },
        {
          id: id("ex"),
          name: "Glute/ham hyperextension",
          targetSets: 4,
          targetReps: "6",
          restSeconds: 60,
          notes: "Low pad, bodyweight if cramping. Straight body, no over-arch.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Smith sumo squat",
          targetSets: 4,
          targetReps: "12",
          restSeconds: 60,
          notes: "Covers the squat pattern. Ramp the first set.",
          category: "legs",
        },
      ],
    },
    {
      id: "day-push-b",
      name: "Push B",
      subtitle: "chest/shoulders · lunge + quad legs",
      exercises: [
        {
          id: id("ex"),
          name: "Bench press",
          targetSets: 4,
          targetReps: "6",
          restSeconds: 120,
          notes: "Heavy — RAMP FIRST: bar → 40 → 60 → 75 → working. Rest to 2 min as load climbs.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Military press",
          targetSets: 3,
          targetReps: "8",
          restSeconds: 90,
          notes: "",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Incline DB press",
          targetSets: 3,
          targetReps: "10",
          restSeconds: 60,
          notes: "",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Cable chest fly",
          targetSets: 4,
          targetReps: "12",
          restSeconds: 45,
          notes: "",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Cable rear delt fly (individual)",
          targetSets: 3,
          targetReps: "15",
          restSeconds: 45,
          notes: "Supinated. Brisk.",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Triceps pushdown",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 45,
          notes: "",
          category: "push",
        },
        {
          id: id("ex"),
          name: "Walking lunges (DB/KB)",
          targetSets: 3,
          targetReps: "10/leg",
          restSeconds: 60,
          notes: "First set bodyweight as a warmup, then loaded.",
          category: "legs",
        },
        {
          id: id("ex"),
          name: "Leg extension",
          targetSets: 3,
          targetReps: "12",
          restSeconds: 60,
          notes: "Maintenance pace.",
          category: "legs",
        },
      ],
    },
  ],
};
